config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :contacts
  root to: 'contacts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:destroy]
  def index
    @contacts = Contact.all
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to contacts_path
    else
      render :new
    end
  end

  def destroy
    if @contact.destroy
      redirect_to contacts_path
    end
  end

  private
  def contact_params
    params.require(:contact).permit(:name, :number, :email)
  end

  def set_contact
    @contact = Contact.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/index.html.erb
<h1>Contacts list</h1> <br>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number</th>
      <th>Email</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.number %></td>
        <td><%= contact.email %></td>
        <td><%= link_to "Delete", contact_path(contact),
          method: :delete,
          data: {confirm: "This contact will move to trash"},
          class:"btn btn-sm btn-outline-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "Add contact", new_contact_path, class:"btn btn-primary" %>

app/views/contacts/new.html.erb
<div class="container">
  <h3>Fill out the form below</h3> <br>

  <%= form_for @contact do |f| %>
    <div class="text-field">
    <%= f.text_field :name, placeholder: "Contact name", required: true, autofocus: true, class:"form-control" %>
    </div> <br>
    <div class="text-field">
    <%= f.text_field :number, placeholder: "Contact number", required: true, class:"form-control" %>
    </div> <br>
    <div class="text-field">
    <%= f.text_field :email, placeholder: "Contact email", required: true, class:"form-control" %>
    </div> <br>

    <div class="actions">
    <%= f.submit "Save contact", class:"btn btn-primary" %>
    <%= link_to "Cancel", contacts_path, class:"btn btn-secondary" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contacts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= current_user.email %>
      <%= link_to "Log out", destroy_user_session_path, class:"btn btn-sm btn-outline-dark" %>
    <% end %>
    <%= yield %>
  </body>
</html>